---
- name: Install and configure Wazuh agent
  hosts: all
  become: yes

  vars:
    wazuh_manager: "10.103.205.52"
    wazuh_registration_password: "password"
    wazuh_agent_group: "Linux"

  tasks:
    - name: Download wazuh-agent package
      get_url:
        url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.3-1_amd64.deb
        dest: /tmp/wazuh-agent_4.7.3-1_amd64.deb

    - name: Install wazuh-agent package
      apt:
        deb: /tmp/wazuh-agent_4.7.3-1_amd64.deb
        state: present

    - name: Set Wazuh manager configuration
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        insertafter: "<client>"
        line: "<server><address>{{ wazuh_manager }}</address></server>"

    - name: Set registration password
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        insertafter: "<client>"
        line: "<auth><password>{{ wazuh_registration_password }}</password></auth>"

    - name: Set agent group
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        insertafter: "<client>"
        line: "<group>{{ wazuh_agent_group }}</group>"

    - name: Start and enable wazuh-agent service
      service:
        name: wazuh-agent
        state: started
        enabled: yes
