---
- name: Change root password on multiple Linux servers
  hosts: all
  become: yes
  vars:
    new_password: "{{ new_password}}"  # Replace with your desired new password
  tasks:
    - name: Change root password
      block:
        - name: Change root password for Ubuntu/Debian
          user:
            name: root
            password: "{{ new_password | password_hash('sha512') }}"
            update_password: always
          when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

        - name: Change root password for Red Hat/CentOS/Oracle Linux
          user:
            name: root
            password: "{{ new_password | password_hash('sha512') }}"
            update_password: always
          when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'OracleLinux'

        # Add more conditions for other distributions if needed

      rescue:
        - debug:
            msg: "Unsupported distribution for changing root password: {{ ansible_distribution }}"

