---
- name: Ping CentOS server
  hosts: nati-desktop
  tasks:
    - name: Ping the server
      ping:
- name: Create user on CentOS
  hosts: nati-desktop
  become: yes

  tasks:
    - name: Create a new user
      user:
        name: testuser
        state: present
        shell: /bin/bash

