---
- name: Ping server and create user on CentOS
  hosts: nati-desktop
  become: yes
  tasks:
    - name: Ping the server
      ping:

    - name: Create a new user
      user:
        name: your_username
        state: present
        shell: /bin/bash


