
---
- name: Create a single user on multiple OS distributions
  hosts: all
  become: yes
  vars:
    username: "{{user_name}}"
    password: "{{password}}"
  tasks:
    - name: Ping the server
      ping:

    - name: Create user on Red Hat/CentOS/Oracle Linux
      user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ password | password_hash('sha512') }}"
      when: ansible_distribution in ['RedHat', 'CentOS', 'OracleLinux']

    - name: Create user on Ubuntu
      user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ password | password_hash('sha512') }}"
      when: ansible_distribution == 'Ubuntu'

      rescue:
        - debug:
            msg: "Unsupported distribution for creating users: {{ ansible_distribution }}"

