---
- name: Get VM details from Nutanix AHV and add to AWX inventory
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Get VM details from Nutanix AHV using curl
      shell: |
        curl -k -u '{{ prism_user }}:{{ prism_password }}' -H 'Content-Type: application/json' -d '{"kind":"vm", "offset":0, "length":100}' https://{{ prism_central_ip }}:9440/api/nutanix/v3/vms/list
      register: vm_list

    - name: Parse VM and IP details
      set_fact:
        vm_details: "{{ vm_list.stdout | from_json }}"
    - name: Get AWX Inventory ID
      uri:
        url: "https://{{ awx_host }}/api/v2/inventories/?name={{ awx_inventory_id }}&organization={{ awx_inventory_organization_id }}"
        method: GET
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        return_content: yes
        headers:
          Content-Type: "application/json"
      register: inventory_id
      failed_when: inventory_id.json.count == 0

    - name: Add VMs to AWX inventory as hosts
      uri:
        url: "{{ awx_host }}/api/v2/hosts/"
        method: POST
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "{{ item.name }}",
            "inventory": "{{ inventory_id.json.results[0].id }}",
            "enabled": true,
            "variables": "ansible_host: {{ item.resources.nic_list[0].ip_endpoint_list[0].ip }}"
          }
        body_format: json
        validate_certs: no
      loop: "{{ vm_details }}"
      when: item.resources.nic_list[0].ip_endpoint_list is defined

    - name: Sync inventory source on AWX
      uri:
        url: "{{ awx_host }}/api/v2/inventory_sources/{{ inventory_id.json.results[0].id }}/update/"
        method: POST
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        headers:
          Content-Type: "application/json"
        body_format: json
        validate_certs: no
