---
- name: Install and Configure Osquery
  hosts: all
  become: yes

  tasks:
    - name: Add Osquery GPG key
      ansible.builtin.shell: |
        curl -L https://pkg.osquery.io/rpm/GPG | tee /etc/pki/rpm-gpg/RPM-GPG-KEY-osquery
      args:
        executable: /bin/bash

    - name: Add Osquery repository
      ansible.builtin.shell: |
        yum-config-manager --add-repo https://pkg.osquery.io/rpm/osquery-s3-rpm.repo
      args:
        executable: /bin/bash

    - name: Enable Osquery repository
      ansible.builtin.shell: |
        yum-config-manager --enable osquery-s3-rpm-repo
      args:
        executable: /bin/bash

    - name: Install Osquery
      ansible.builtin.yum:
        name: osquery
        state: present

    - name: Create /etc/osquery directory if it doesn't exist
      ansible.builtin.file:
        path: /etc/osquery
        state: directory
        mode: '0755'

    - name: Add Osquery configuration via environment variable
      ansible.builtin.copy:
        dest: /etc/osquery/osquery.conf
        content: |
          {
              "options": {
                  "config_plugin": "filesystem",
                  "logger_plugin": "filesystem",
                  "utc": "true"
              },
              "schedule": {
                  "system_info": {
                      "query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
                      "interval": 3600
                  },
                  "high_load_average": {
                      "query": "SELECT period, average, '70%' AS 'threshold' FROM load_average WHERE period = '15m' AND average > '0.7';",
                      "interval": 900,
                      "description": "Report if load charge is over 70 percent."
                  },
                  "low_free_memory": {
                      "query": "SELECT memory_total, memory_free, CAST(memory_free AS real) / memory_total AS memory_free_perc, '10%' AS threshold FROM memory_info WHERE memory_free_perc < 0.1;",
                      "interval": 1800,
                      "description": "Free RAM is under 10%."
                  }
              },
              "packs": {
                  "osquery-monitoring": "/opt/osquery/share/osquery/packs/osquery-monitoring.conf",
                  "incident-response": "/opt/osquery/share/osquery/packs/incident-response.conf",
                  "it-compliance": "/opt/osquery/share/osquery/packs/it-compliance.conf",
                  "vuln-management": "/opt/osquery/share/osquery/packs/vuln-management.conf",
                  "hardware-monitoring": "/opt/osquery/share/osquery/packs/hardware-monitoring.conf",
                  "ossec-rootkit": "/opt/osquery/share/osquery/packs/ossec-rootkit.conf"
              }
          }

    - name: Restart Osquery service
      ansible.builtin.systemd:
        name: osqueryd
        state: restarted
