---
- name: Configure system warning and SSH banner
  hosts: Wazuh
  become: yes  # Apply privilege escalation globally

  tasks:
    - name: Add warning message to /etc/issue
      ansible.builtin.blockinfile:
        path: /etc/issue
        block: |
          *************************************Warning***************************************
           This system is for the use of authorized users only. Any or all uses of this      
           system and all files on this system may be intercepted, monitored, recorded,      
           copied, audited, inspected and disclosed to authorized organizational and law     
           enforcement personnel. Your access is strictly limited to applicable services     
           of the system for which you have obtained written authorization, and will be      
           governed by the organization's security policy & acceptable usage standard.       
           Unauthorized or improper use of this system is strictly prohibited and may        
           result in administrative disciplinary action and/or civil charges/criminal        
           penalties. By continuing to use this system, you indicate your awareness of       
           and consent to the terms and conditions of use. LOG OFF IMMEDIATELY (press CTRL-C)
           if you do not agree to the conditions stated in this warning.                     
          **************************************Warning**************************************
        create: yes
        mode: '0644'
        owner: root
        group: root
        unsafe_writes: true
      become: yes  # Ensure Ansible runs this task as root

    - name: Ensure Banner line exists in /etc/ssh/sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Banner'
        line: 'Banner /etc/issue'
      become: yes  # Required to modify SSH config

    - name: Restart SSH service
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      become: yes  # Ensure we have root privileges for restarting SSH
