---
- name: Upgrade RHEL 8.3 to 8.10 online with subscription registration
  hosts: all
  become: true
  vars:
    rhsm_username: "talilem"
    rhsm_password: "MiWaBu3220cbo"

  tasks:
    - name: Clean subscription-manager data
      command: subscription-manager clean

    - name: Restart rhsm service
      systemd:
        name: rhsm.service
        state: restarted
        daemon_reload: yes

    - name: Register system to Red Hat Subscription Manager
      command: >
        subscription-manager register
        --force
        --username {{ rhsm_username }}
        --password {{ rhsm_password }}
        --autosubscribe
      register: reg_result
      changed_when: "'System has been registered' in reg_result.stdout or reg_result.rc == 0"
      failed_when: reg_result.rc not in [0, 64]  # 64 = already registered

    - name: Refresh subscription manager
      command: subscription-manager refresh
      when: reg_result.changed or reg_result.rc == 0

    - name: Enable required RHEL 8 repos
      command: >
        subscription-manager repos
        --enable=rhel-8-for-x86_64-baseos-rpms
        --enable=rhel-8-for-x86_64-appstream-rpms

    - name: Clean DNF cache
      command: dnf clean all

    - name: Remove cached metadata
      file:
        path: /var/cache/dnf
        state: absent

    - name: Update all packages to latest (8.10) with allowerasing to fix conflicts
      command: dnf update -y --allowerasing

    - name: Reboot system
      reboot:
        msg: "Rebooting after RHEL upgrade"
        reboot_timeout: 1200

    - name: Check RHEL version after reboot
      command: cat /etc/redhat-release
      register: version_check

    - name: Show upgraded RHEL version
      debug:
        msg: "System is now running: {{ version_check.stdout }}"
