---
- name: Offline patch RHEL 8 using mounted ISO
  hosts: all
  become: true
  vars:
    iso_file: /dev/sr0
    mount_path: /mnt/rhel8-10
    repo_file: /etc/yum.repos.d/rhel8-10-offline.repo
  tasks:

    - name: Ensure mount point exists
      file:
        path: "/mnt/rhel8-10"
        state: directory

    - name: Mount RHEL 8 ISO to /mnt/rhel8-10
      mount:
        src: "/dev/sr0"
        path: "/mnt/rhel8-10"
        fstype: iso9660
        opts: loop,ro
        state: mounted

    - name: Create offline repo pointing to ISO
      copy:
        dest: "/etc/yum.repos.d/rhel8-10-offline.repo"
        content: |
          [rhel8-BaseOS]
          name=RHEL 8 BaseOS from ISO
          baseurl=file:///mnt/rhel8-10/BaseOS
          enabled=1
          gpgcheck=0

          [rhel8-AppStream]
          name=RHEL 8 AppStream from ISO
          baseurl=file:///mnt/rhel8-10/AppStream
          enabled=1
          gpgcheck=0
        mode: '0644'

    - name: Disable all other repositories (optional for safety)
      command: dnf config-manager --disable \*
      ignore_errors: true

    - name: Clean DNF metadata
      command: dnf clean all

    - name: Rebuild DNF cache from ISO
      command: dnf makecache

    - name: Remove libstdc++-static.i686
      dnf:
        name: libstdc++-static.i686
        state: absent


    - name: Update all packages using offline ISO repos
      dnf:
        name: '*'
        state: latest
        disablerepo: '*'
        enablerepo: rhel8-BaseOS,rhel8-AppStream

    - name: Unmount ISO
      mount:
        path: "/mnt/rhel8-10"
        state: unmounted

    - name: Remove offline repo file
      file:
        path: "/etc/yum.repos.d/rhel8-10-offline.repo"
        state: absent
