---
- name: Enforce Password Complexity and Session Timeout on Ubuntu 22.04
  hosts: all
  become: true
  become_method: sudo

  vars:
    pwquality_conf: |
      minlen = 12
      dcredit = -1
      ucredit = -1
      lcredit = -1
      ocredit = -1
      minclass = 4
      retry = 6
      enforce_for_root

    pam_pwquality_line: "password requisite pam_pwquality.so retry=6 minlen=12 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1"
    
    auto_logout: |
      TMOUT=900
      readonly TMOUT
      export TMOUT

  tasks:

    - name: Install required PAM packages
      apt:
        name: libpam-pwquality
        state: present
        update_cache: yes

    - name: Backup common-password before changes
      copy:
        src: /etc/pam.d/common-password
        dest: /etc/pam.d/common-password.bak
        remote_src: yes
        backup: yes

    - name: Ensure pam_pwquality line is present in common-password
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+requisite\s+pam_pwquality\.so.*'
        line: "{{ pam_pwquality_line }}"
        insertafter: '^[#@]?password'

    - name: Configure pwquality.conf
      copy:
        dest: /etc/security/pwquality.conf
        content: "{{ pwquality_conf }}"
        mode: '0644'

    - name: Set session timeout (auto logout after 15 minutes)
      copy:
        dest: /etc/profile.d/autologout.sh
        content: "{{ auto_logout }}"
        mode: '0755'
