---
- name: Enforce strict password policy via pwquality.conf
  hosts: all
  become: true
  vars:
    desired_pwquality_settings:
      difok: '5'
      minlen: '12'
      dcredit: '-1'
      ucredit: '-1'
      lcredit: '-1'
      ocredit: '-1'
      minclass: '4'

  tasks:

    - name: Ensure libpam-pwquality is installed
      apt:
        name: libpam-pwquality
        state: present
        update_cache: yes

    - name: Backup original pwquality.conf
      copy:
        src: /etc/security/pwquality.conf
        dest: /etc/security/pwquality.conf.bak
        remote_src: yes
        backup: yes

    - name: Read current pwquality.conf
      slurp:
        src: /etc/security/pwquality.conf
      register: pwqfile

    
