---
- name: Enforce strict password policy and set password expiry for existing users
  hosts: all
  become: true

  tasks:
    - name: Replace /etc/security/pwquality.conf content
      copy:
        dest: /etc/security/pwquality.conf
        content: |
          difok = 5
          minlen = 12
          dcredit = -1
          ucredit = -1
          lcredit = -1
          ocredit = -1
          minclass = 4
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Set password expiry for existing users (excluding system users and root)
      command: chage --maxdays 90 --mindays 0 --warndays 7 {{ item }}
      loop: "{{ lookup('ansible.builtin.pipe', \"awk -F: '$3 >= 1000 && $1 != \\\"root\\\" {print $1}' /etc/passwd\").splitlines() }}"



    
