---
- name: Enforce Security Hardening Policy on Ubuntu 22.04
  hosts: all
  become: true
  become_method: sudo

  vars:
    password_policy_applied_after: "2025-07-02"

    pwquality_conf: |
      minlen = 12
      dcredit = -1
      ucredit = -1
      lcredit = -1
      ocredit = -1
      minclass = 4
      retry = 6
      enforce_for_root

    auto_logout: |
      TMOUT=900
      readonly TMOUT
      export TMOUT

    login_defs_conf:
      - { regexp: '^PASS_MAX_DAYS', line: 'PASS_MAX_DAYS   90' }
      - { regexp: '^PASS_MIN_DAYS', line: 'PASS_MIN_DAYS   0' }
      - { regexp: '^PASS_WARN_AGE', line: 'PASS_WARN_AGE   7' }

    pam_pwquality_line: "password requisite pam_pwquality.so retry=6 minlen=12 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1"
    pam_unix_line: "password sufficient pam_unix.so sha512 shadow try_first_pass use_authtok remember=4"
    pam_faillock_pre_line: "auth required pam_faillock.so preauth silent deny=6 unlock_time=1800"
    pam_faillock_authfail_line: "auth [default=die] pam_faillock.so authfail deny=6 unlock_time=1800"
    pam_faillock_account_line: "account required pam_faillock.so"

  tasks:

    - name: Install required PAM packages
      apt:
        name:
          - libpam-pwquality
          - libpam-modules
        state: present
        update_cache: yes

    - name: Backup PAM files
      copy:
        src: "/etc/pam.d/{{ item }}"
        dest: "/etc/pam.d/{{ item }}.bak"
        remote_src: yes
        backup: yes
      loop:
        - common-password
        - common-auth
        - common-account

    - name: Ensure pam_pwquality line exists in common-password
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+requisite\s+pam_pwquality\.so.*'
        line: "{{ pam_pwquality_line }}"
        insertafter: '^[#@]?password'

    - name: Ensure password history (remember last 4)
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+sufficient\s+pam_unix\.so.*'
        line: "{{ pam_unix_line }}"
        insertafter: '^password\s+requisite\s+pam_pwquality\.so.*'

    - name: Configure /etc/security/pwquality.conf
      copy:
        dest: /etc/security/pwquality.conf
        content: "{{ pwquality_conf }}"
        mode: '0644'

    - name: Add account lockout policy to common-auth
      block:
        - name: Insert pam_faillock preauth
          lineinfile:
            path: /etc/pam.d/common-auth
            regexp: '^auth\s+required\s+pam_faillock\.so preauth.*'
            line: "{{ pam_faillock_pre_line }}"
            insertafter: '^#?auth'

        - name: Insert pam_faillock authfail
          lineinfile:
            path: /etc/pam.d/common-auth
            regexp: '^auth\s+\[default=die\]\s+pam_faillock\.so authfail.*'
            line: "{{ pam_faillock_authfail_line }}"
            insertafter: '^auth.*pam_faillock\.so preauth.*'

        - name: Insert pam_faillock account
          lineinfile:
            path: /etc/pam.d/common-account
            regexp: '^account\s+required\s+pam_faillock\.so'
            line: "{{ pam_faillock_account_line }}"
            insertafter: '^#?account'

    - name: Set password expiry policy in login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop: "{{ login_defs_conf }}"

    - name: Set session timeout policy
      copy:
        dest: /etc/profile.d/auto
