---
- name: Enforce strict password policy via pwquality.conf
  hosts: all
  become: true
  vars:
    desired_pwquality_settings:
      difok: '5'
      minlen: '12'
      dcredit: '-1'
      ucredit: '-1'
      lcredit: '-1'
      ocredit: '-1'
      minclass: '4'

  tasks:

    - name: Ensure libpam-pwquality is installed
      apt:
        name: libpam-pwquality
        state: present
        update_cache: yes

    - name: Backup original pwquality.conf
      copy:
        src: /etc/security/pwquality.conf
        dest: /etc/security/pwquality.conf.bak
        remote_src: yes
        backup: yes

    - name: Read current pwquality.conf
      slurp:
        src: /etc/security/pwquality.conf
      register: pwqfile

    - name: Rewrite pwquality.conf with enforced settings
      copy:
        dest: /etc/security/pwquality.conf
        content: |
          {%- set existing_lines = pwqfile.content | b64decode().splitlines() %}
          {%- set keys_to_keep = desired_pwquality_settings.keys() | list %}

          # Managed by Ansible - password policy
          {%- for key, val in desired_pwquality_settings.items() %}
          {{ key }} = {{ val }}
          {%- endfor %}

          # Commented out previous settings not in managed list
          {%- for line in existing_lines %}
            {%- if line.strip() and not line.strip().startswith('#') %}
              {%- set parts = line.split('=') %}
              {%- set key = parts[0].strip() %}
              {%- if key not in keys_to_keep %}
            # {{ line }}
              {%- endif %}
             {%- endif %}
             {%- endfor %}
