---
- name: Enforce password policy using pwquality.conf
  hosts: all
  become: yes
  tasks:

    - name: Ensure pwquality package is installed
      apt:
        name: libpam-pwquality
        state: present
        update_cache: yes

    - name: Set password policy in /etc/security/pwquality.conf
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^{{ item.key }}\s*='
        line: '{{ item.key }} = {{ item.value }}'
        create: yes
        state: present
        backrefs: yes
      loop:
        - { key: 'difok', value: '5' }
        - { key: 'minlen', value: '12' }
        - { key: 'dcredit', value: '-1' }
        - { key: 'ucredit', value: '-1' }
        - { key: 'lcredit', value: '-1' }
        - { key: 'ocredit', value: '-1' }
        - { key: 'minclass', value: '4' }
