---
- name: Overwrite pwquality.conf with strict password policy
  hosts: all
  become: true

  tasks:
    - name: Replace /etc/security/pwquality.conf content
      copy:
        dest: /etc/security/pwquality.conf
        content: |
          difok = 5
          minlen = 12
          dcredit = -1
          ucredit = -1
          lcredit = -1
          ocredit = -1
          minclass = 4
        owner: root
        group: root
        mode: '0644'
        backup: yes

    
