---
- name: Enforce Windows Password Policy and Session Timeout
  hosts: all
  gather_facts: false
  vars:
    policy_inf_path: C:\Temp\password_policy.inf
    policy_db_path: C:\Windows\security\local_policy.sdb

  tasks:

    - name: Ensure C:\Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Create password policy INF file
      win_copy:
        dest: "{{ policy_inf_path }}"
        content: |
          [Unicode]
          Unicode=yes
          [System Access]
          PasswordComplexity = 1
          MinimumPasswordLength = 12
          PasswordHistorySize = 4
          MaximumPasswordAge = 90
          MinimumPasswordAge = 0
          LockoutBadCount = 6
          ResetLockoutCount = 30
          LockoutDuration = 30

    - name: Set minimum password length
      community.windows.win_security_policy:
         name: MinimumPasswordLength
         policy_value: 12



    - name: Restart Netlogon service to ensure MinimumPasswordLength applies
      win_service:
        name: Netlogon
        state: restarted

    - name: Remove temporary INF file
      win_file:
        path: "{{ policy_inf_path }}"
        state: absent

    - name: Set Session Timeout to 15 minutes (900 seconds)
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: ScreenSaveTimeOut
        data: "900"
        type: string

    - name: Enable Screen Saver
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: ScreenSaveActive
        data: "1"
        type: string

    - name: Set Screen Saver Executable
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: SCRNSAVE.EXE
        data: logon.scr
        type: string

    - name: Force Group Policy update
      win_shell: gpupdate /force

    - name: Reboot host to finalize policy
      win_reboot:
        reboot_timeout: 600
