---
- name: Enforce Windows Password Policy and Session Timeout (Reliable)
  hosts: windows
  gather_facts: false
  vars:
    policy_inf_path: C:\Temp\password_policy.inf

  tasks:

    # ----------------------------
    # PASSWORD POLICY SECTION
    # ----------------------------

    - name: Create password policy INF file
      win_copy:
        dest: "{{ policy_inf_path }}"
        content: |
          [System Access]
          PasswordComplexity = 1
          PasswordHistorySize = 4
          MaximumPasswordAge = 90
          MinimumPasswordAge = 0

    - name: Apply password policy using secedit
      win_shell: |
        secedit /configure /db C:\Windows\security\local.sdb /cfg {{ policy_inf_path }} /areas SECURITYPOLICY
      register: secedit_result

    - name: Enforce minimum password length via registry (MinLength = 12)
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
        name: MinimumPasswordLength
        data: 12
        type: dword

    - name: Remove temporary INF file
      win_file:
        path: "{{ policy_inf_path }}"
        state: absent

    # ----------------------------
    # SESSION TIMEOUT SECTION
    # ----------------------------

    - name: Set Session Timeout to 15 minutes (900 seconds)
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: ScreenSaveTimeOut
        data: "900"
        type: string

    - name: Enable Screen Saver
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: ScreenSaveActive
        data: "1"
        type: string

    - name: Set Screen Saver Executable
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: SCRNSAVE.EXE
        data: logon.scr
        type: string

    - name: Show secedit output
      debug:
        var: secedit_result.stdout_lines
