---
- name: Enforce Windows Password Policy and Session Timeout
  hosts: all
  gather_facts: false
  vars:
    policy_inf_path: C:\Temp\password_policy.inf
    policy_db_path: C:\Windows\security\local_policy.sdb

  tasks:

   - name: Ensure C:\Temp directory exists
     win_file:
      path: C:\Temp
      state: directory

   - name: Create password policy INF file
     win_copy:
       dest: "{{ policy_inf_path }}"
       content: |
        [Unicode]
        Unicode=yes

        [System Access]
        PasswordComplexity = 1
        MinimumPasswordLength = 12
        PasswordHistorySize = 4
        MaximumPasswordAge = 90
        MinimumPasswordAge = 0
        LockoutBadCount = 6
        ResetLockoutCount = 30
        LockoutDuration = 30

- name: Wait for INF file to be fully written
  pause:
    seconds: 3

- name: Verify INF file exists and is accessible
  win_stat:
    path: "{{ policy_inf_path }}"
  register: inf_file_stat

- debug:
    var: inf_file_stat

- name: Apply password policy using secedit
  win_shell: >
    secedit /configure /db "C:\Windows\security\local_policy_test.sdb"
    /cfg "{{ policy_inf_path }}" /areas SECURITYPOLICY
  register: secedit_result

- name: Print secedit output
  debug:
    var: secedit_result.stdout_lines

    - name: Print secedit result
      debug:
        var: secedit_result.stdout_lines

    - name: Force computer policy refresh
      win_shell: gpupdate /target:computer /force

    - name: Remove temporary INF file
      win_file:
        path: "{{ policy_inf_path }}"
        state: absent

    - name: Reboot host to finalize policy
      win_reboot:
        reboot_timeout: 600

    - name: Set Session Timeout to 15 minutes (900 seconds)
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: ScreenSaveTimeOut
        data: "900"
        type: string

    - name: Enable Screen Saver
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: ScreenSaveActive
        data: "1"
        type: string

    - name: Set Screen Saver Executable
      win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: SCRNSAVE.EXE
        data: logon.scr
        type: string

    - name: Validate current password policy
      win_shell: net accounts
      register: pw_policy

    - name: Display password policy result
      debug:
        var: pw_policy.stdout_lines
