
---
- name: Update Windows Server Patches
  hosts: all
  gather_facts: no
  tasks:

    - name: Install all available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        reboot: yes
