---
- name: Enforce Windows Password, Lockout, and Session Timeout Policies
  hosts: all
  gather_facts: false
  vars:
    lockout_threshold: 6
    lockout_duration: 30         # minutes
    lockout_reset: 30            # minutes
    password_min_length: 12
    password_complexity: 1       # 1 = enabled
    password_history: 4
    password_max_age: 90           # days
    session_timeout_seconds: 900   # 15 minutes

  tasks:
    ## --- PASSWORD POLICIES ---

    - name: Set Minimum Password Length
      community.windows.win_security_policy:
        section: System Access
        key: MinimumPasswordLength
        value: "{{ password_min_length }}"

    - name: Enforce Password Complexity (1 = enabled)
      community.windows.win_security_policy:
        section: System Access
        key: PasswordComplexity
        value: "{{ password_complexity }}"

    - name: Enforce Password History (Remember last X)
      community.windows.win_security_policy:
        section: System Access
        key: PasswordHistorySize
        value: "{{ password_history }}"

    - name: Set Maximum Password Age
      community.windows.win_security_policy:
        section: System Access
        key: MaximumPasswordAge
        value: "{{ password_max_age }}"

    ## --- ACCOUNT LOCKOUT POLICIES ---

    - name: Set Account Lockout Threshold
      community.windows.win_security_policy:
        section: System Access
        key: LockoutBadCount
        value: "{{ lockout_threshold }}"

    - name: Set Lockout Duration (minutes)
      community.windows.win_security_policy:
        section: System Access
        key: LockoutDuration
        value: "{{ lockout_duration }}"

    - name: Set Lockout Reset Time (Observation Window)
      community.windows.win_security_policy:
        section: System Access
        key: ResetLockoutCount
        value: "{{ lockout_reset }}"

    ## --- SESSION TIMEOUT (IDLE LOGOUT) POLICIES ---

    - name: Set Screen Saver Timeout (Idle time before lockout in seconds)
      community.windows.win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: ScreenSaveTimeOut
        data: "{{ session_timeout_seconds }}"
        type: string

    - name: Enable Screen Saver (Required for timeout policy)
      community.windows.win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: ScreenSaveActive
        data: "1"
        type: string

    - name: Set Screen Saver Executable (optional)
      community.windows.win_regedit:
        path: HKCU:\Control Panel\Desktop
        name: SCRNSAVE.EXE
        data: logon.scr
        type: string
