---
- name: Configure NTP Client and Timezone on Windows Server 2019
  hosts: all
  gather_facts: false

  collections:
    - ansible.windows

  vars:
    ntp_server: "10.100.4.111"
    timezone_name: "E. Africa Standard Time"  # Windows timezone name for Africa/Djibouti

  tasks:

    - name: Set Windows Timezone to Africa/Djibouti
      win_timezone:
        timezone: "{{ timezone_name }}"

    - name: Configure NTP Server
      win_shell: |
        w32tm /config /manualpeerlist:"{{ ntp_server }}" /syncfromflags:manual /update

    - name: Enable NTP Client via Registry
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpClient
        name: Enabled
        data: 1
        type: dword

    - name: Ensure Windows Time service is set to Auto
      win_service:
        name: w32time
        start_mode: auto

    - name: Restart Windows Time service
      win_service:
        name: w32time
        state: restarted

    - name: Force Time Resync
      win_shell: w32tm /resync
      register: resync_output
      failed_when: "'The service has not been started' in resync_output.stderr"

    - name: Show NTP Sync Output
      debug:
        var: resync_output.stdout_lines
