---
- name: Your play name
  hosts: all
  gather_facts: false

  tasks:
    - name: Copy password policy INF file
      win_copy:
        dest: C:\Temp\password_policy.inf
        content: |
          [System Access]
          MinimumPasswordLength = 12
          PasswordComplexity = 1
          PasswordHistorySize = 4
          MaximumPasswordAge = 90
          MinimumPasswordAge = 0
          LockoutBadCount = 6
          ResetLockoutCount = 30
          LockoutDuration = 30

    - name: Apply password policy using secedit
      win_shell: secedit /configure /db C:\Windows\security\local.sdb /cfg C:\Temp\password_policy.inf /areas SECURITYPOLICY

    - name: Force group policy update
      win_shell: gpupdate /force

    - name: Reboot host to apply policies
      win_reboot:
        reboot_timeout: 600
