---
- name: Configure NTP Client on Windows Server 2019
  hosts: all
  gather_facts: false
  vars:
    ntp_server: "10.1.75.111"
    timezone_name: "Africa/Djibouti"

  tasks:

    - name: Set Windows Timezone
      win_timezone:
        timezone: "{{ timezone_name }}"

    - name: Set NTP Server Configuration
      win_shell: |
        w32tm /config /manualpeerlist:"{{ ntp_server }}" /syncfromflags:manual /update

    - name: Enable NTP Client via Registry
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpClient
        name: Enabled
        data: 1
        type: dword

    - name: Ensure Windows Time service is set to Automatic
      win_service:
        name: w32time
        start_mode: auto

    - name: Start Windows Time service
      win_service:
        name: w32time
        state: started

    - name: Restart Windows Time service
      win_service:
        name: w32time
        state: restarted

    - name: Force Time Resync
      win_shell: w32tm /resync
      register: resync_output
      failed_when: "'The service has not been started' in resync_output.stderr"

    - name: Query NTP Sync Status
      win_shell: w32tm /query /status
      register: ntp_status

    - name: Show NTP Sync Output
      debug:
        var: ntp_status.stdout_lines
